config/routes.rb
Rails.application.routes.draw do

	resources :trees

end

app/models/tree.rb
class Tree < ActiveRecord::Base

	has_attached_file :file

	validates_attachment :file,
  :content_type => { :content_type => "text/plain" },
  :size => { :in => 0..10.megabytes }

	validates :accuracy, numericality: true #requires number input, converts to float
	validates :pr_id, :presence => true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/trees_controller.rb
class TreesController < ApplicationController
 
  protect_from_forgery with: :null_session

  # snipped for brevity

	def new
  	@tree = Tree.new
	end

	def create
		@tree = Tree.create(tree_params)

		respond_to do |format|
			if @tree.save
				format.html{redirect_to @tree}
				format.json{render :json => @tree, :status => :created, :location => @tree }
			else
				format.html { render 'new' }
				format.json { render json: @tree.errors, status: :unprocessable_entity }
			end
		end
	end

	def index
		@trees = Tree.all
	end

	def edit
		@tree = Tree.find(params[:id])
	end

	def update
	@tree = Tree.find(params[:id])

    respond_to do |format|
      if @tree.update(tree_params)
				@tree.file = params[:tree][:file]
        format.html { redirect_to @tree}
        format.json { head :no_content }
      else
        format.html { render 'edit' }
        format.json { render json: @tree.errors, status: :unprocessable_entity }
      end
		end
	end

	def show
		@tree = Tree.find(params[:id])
		if @tree.file.exists? == true
			@tree.model = File.read(@tree.file.path)
		end
	end

	private
		def tree_params
			params.require(:tree).permit(:note, :pr_id, :model_type, :accuracy, :file, :model)
		end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Petosky</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/trees/edit.html.erb
<h1> <%= link_to 'Index', trees_path %></h1>
<h1>Editing tree metadata</h1>
 
<%= form_for @tree, :url => tree_path, :html => { :multipart => true }, method: :patch do |f| %>
  <% if @tree.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@tree.errors.count, "error") %> prohibited
      this tree metadata from being saved:</h2>
    <ul>
    <% @tree.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>

	  <p>
    <%= f.label :model_type %><br>
    <%= f.text_field :model_type %>
  </p>

	  <p>
    <%= f.label :accuracy %><br>
    <%= f.text_area :accuracy %>
  </p>

  <p>
    <%= f.label "Target Domain / Pr"  %><br>
    <%= f.text_area :pr_id %>
  </p>

  <p>
    <%= f.label :note %><br>
    <%= f.text_area :note %>
  </p>

<h2> Change the Model File.txt (only recommended for errors):</h2>

		<%= f.file_field :file %> </br></br>
		<%= f.submit %>
<% end %>

app/views/trees/index.html.erb
<%= stylesheet_link_tag "application", media: "all" %>

<h1>Tree Models</h1>

<b>To create a new model using POST with a JSON object: </b>

<p>Use curl:</p> 

<p>curl -X POST -H "Content-Type: application/json" -d '{ "tree" :
	{ 
	"author" : "your name here" ,  
	"note" : "any notes you have" ,
	"pr_id" : "some feature of interest - not optional" ,
	"model_type" : "tree - not optional" ,
	"accuracy" : "0.00" , 
	"model" : " your matlab text here - not optional"
	}
}' localhost:3000/trees.json </p>

 
<h2><%= link_to 'Add a new tree model', new_tree_path %></h2>

<table>
  <tr>
    <th>Domain</th>
    <th>Accuracy</th>
    <th colspan="5"></th>
  </tr>
 
<% @trees.each do |tree| %>
  <tr>
    <td><%= tree.pr_id %></td>
    <td><%= tree.accuracy %></td>
    <td><%= link_to 'HTML', tree_path(tree) %></td>
		<td><%= link_to 'JSON', polymorphic_path( tree, :format => :json ) %></td>
    <td> --- <%= link_to 'Edit', edit_tree_path(tree) %></td>
  </tr>
<% end %>
</table>

app/views/trees/new.html.erb
<h1> <%= link_to 'Index', trees_path %> </h1>

<h1>New Tree Metadata</h1>

<%= form_for @tree, url: {action: "create"}, html: {multipart: true } do |f| %>

	<% if @tree.errors.any? %>
	  <div id="error_explanation">
		<h2><%= pluralize(@tree.errors.count, "error") %> prohibited
		  this tree metadata from being saved:</h2>
		<ul>
		<% @tree.errors.full_messages.each do |msg| %>
		  <li><%= msg %></li>
		<% end %>
		</ul>
	  </div>
	<% end %>

  <p>
    <%= f.label :model_type %><br>
    <%= f.text_field :model_type %>
  </p>

  <p>
    <%= f.label "Target Domain / PR Id" %><br>
    <%= f.text_area :pr_id %>
  </p>
 
  <p>
    <%= f.label :accuracy %><br>
    <%= f.text_area :accuracy %>
  </p>

  <p>
    <%= f.label :note %><br>
    <%= f.text_area :note %>
  </p>

<h2> Add the model file (extension .txt) </h2>
	  <p>
   	<%= f.file_field :file %> </br>
  </p>
 
	<p> ### </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/trees/show.html.erb
<h1><%= link_to 'Index', trees_path %></h1>

<h1>Tree Model Metadata</h1>

<p>
  <strong>Accuracy:</strong>
  <%= @tree.accuracy %>
</p>

<p>
  <strong>Model Type:</strong>
  <%= @tree.model_type %>
</p>

<p>
  <strong>Purple Robot Name:</strong>
  <%= @tree.pr_id %>
</p>

<p>
  <strong>Note:</strong>
  <%= @tree.note %>
</p>

<p>
	<strong>Model File:</strong>
	<%= link_to 'Right Here', @tree.file.url %>
</p>

<p>
	<strong>Model String:</strong>
	<%= @tree.model %>
</p>

app/views/trees/show.json.erb
{
"accuracy" : <%= @tree.accuracy %>,
"model_type" :  "<%= @tree.model_type %>",
"name" : "<%= @tree.pr_id %>",
"model" : "<%= @tree.model.html_safe %>"
}